### ISSUE TITLE
Enabling Debug Mode fails in Latest AMI

### ISSUE THREAD

**Issue by affoliveira-aws** [awslabs/aws-ecs-logs-collector-for-windows#1]
Running the script in debug mode or enabling debug mode fails because the script relied on stoping and starting the ecs agent scheduled task to start the agent in debug mode.

Since latest AMI, the ecs agent has moved from a scheduled task to a service

**Comment by O1moore** [comment]
Can confirm this issue was present in latest ECS Windows AMI ami-e6c4249b, see PR for fix

**Comment by O1moore** [comment]
fixed merged, PR #2
